name: Node.js CI

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }} 
    - name: Create .npmrc file
      uses: FerLuisxd/create-npmrc@3
      with:
        org_name: domipas  
        auth_token: ${{secrets.NPM_TOKEN}}
      env:
        AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - run: npm test
